name: Publish Gitbook

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

      
    - name: npm install gitbook
      run: |
        npm install -g gitbook-cli

    - name: build Gitbook
      run: |
        build_dir() {
          DIR="$1"
          pushd $DIR
          rsync -rv ../_layouts/ ./_layouts/
          rsync -rv ../resources/ ./resources/
          gitbook init
          gitbook install
          gitbook build
          popd
        }
        build_dir zh_cn
        build_dir en
        build_dir ru
        build_dir ko
        build_dir fa
        build_dir vi

    - name: Gitbook Publish
      env:
        PUBUSER: ${{ secrets.PUBLISH_USER }}
        PUBTOKEN: ${{ secrets.PUBLISH_TOKEN }}
      run: |
        TARGET_DIR=_v2ray_com
        git clone "https://github.com/v2fly/v2fly-github-io.git" ${TARGET_DIR}

        pushd ${TARGET_DIR}
        git config user.name "Bot V2FlyContrib"
        git config user.email "50686256+V2FlyContrib@users.noreply.github.com"
        git reset --hard $(git rev-list --max-parents=0 --abbrev-commit HEAD)
        popd

        rm -rf ${TARGET_DIR}/*
        cp -r ./zh_cn/_book/* ${TARGET_DIR}/
        mkdir ${TARGET_DIR}/en/
        cp -r ./en/_book/* ${TARGET_DIR}/en/
        mkdir ${TARGET_DIR}/ru/
        cp -r ./ru/_book/* ${TARGET_DIR}/ru/
        mkdir ${TARGET_DIR}/ko/
        cp -r ./ko/_book/* ${TARGET_DIR}/ko/
        mkdir ${TARGET_DIR}/fa/
        cp -r ./fa/_book/* ${TARGET_DIR}/fa/
        mkdir ${TARGET_DIR}/vi/
        cp -r ./vi/_book/* ${TARGET_DIR}/vi/
        cp -r ./_dev/* ${TARGET_DIR}/
        cp -v CNAME ${TARGET_DIR}/
        cp -v robots.txt ${TARGET_DIR}/
        cp -r ./resources/* ${TARGET_DIR}/resources/

        pushd ${TARGET_DIR}
        git add -A
        git commit -m 'update'
        git push -f "https://${PUBUSER}:${PUBTOKEN}@github.com/v2fly/v2fly-github-io.git" master
